px4adrc:
  ros__parameters:
    topics:
      reference: /px4adrc/reference
      start_tracking: /mission/start_tracking1
    mission:
      takeoff_target_z: -1.0
      takeoff_z_threshold: 0.2
      takeoff_hold_time_s: 5.0
      reference_timeout_s: 0.3
    vehicle:
      mass_kg: 2.0643076923076915
      gravity: 9.81
      inertia_diag: [0.02384669, 0.02394962, 0.04399995]
      arm_length_m: 0.246073
      yaw_moment_coeff: 0.016
      max_total_thrust_n: 60.0
    motors:
      thrust_model_factor: 1.0
    position_adrc:
      max_tilt_deg: 12.0
      td_r: [1.0, 1.0, 2.0]
      eso_beta1: [0.1, 0.1, 6.0]
      eso_beta2: [0.6, 0.6, 30.0]
      eso_beta3: [1.0, 1.0, 60.0]
      eso_b0: [1.0, 1.0, 1.0]
      nlsef_k1: [0.8, 0.8, 2.0]
      nlsef_k2: [0.2, 0.2, 1.0]
      nlsef_alpha1: [0.8, 0.8, 0.8]
      nlsef_alpha2: [0.5, 0.5, 0.5]
      nlsef_delta: [0.01, 0.01, 0.01]
    attitude_adrc:
      attitude_td_r: [3.2, 3.2, 0.0]
      attitude_eso_beta1: [0.0, 0.0, 0.0]
      attitude_eso_beta2: [0.0, 0.0, 0.0]
      attitude_eso_beta3: [0.0, 0.0, 0.0]
      attitude_eso_b0: [0.0, 0.0, 0.0]
      attitude_nlsef_k1: [3.5, 3.5, 0.0]
      attitude_nlsef_k2: [0.38, 0.38, 0.0]
      attitude_nlsef_alpha1: [1.0, 1.0, 1.0]
      attitude_nlsef_alpha2: [1.0, 1.0, 1.0]
      attitude_nlsef_delta: [0.01, 0.01, 0.01]
